name: irctc-backend

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Amanjain@2026
      POSTGRES_DB: Ictrc_User
    ports:
      - "5433:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - postgres

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command: redis-server --requirepass Amannn_jn
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    restart: always
    ports:
      - "8001:5540"
    depends_on:
      - redis

volumes:
  postgres_data:
  redis_data:
